### ISSUE TITLE
Where are the datasets?

### ISSUE THREAD

**Issue by wyqnumber** [binga/AnalyticsVidhya_BlackFriday#1]
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
submit = pd.read_csv("Sample_Submission_Tm9Lura.csv")

"The dataset is accessible only if the contest is active." in http://datahack.analyticsvidhya.com/contest/black-friday-data-hack

Thank you!

**Comment by binga** [comment]
I have shared the datasets on Google Drive. You can download them here. — https://drive.google.com/folderview?id=0B4-c0K3SnXFcbWFRbjNUaWl1ekU&usp=sharing

Extract the train and test zip files and rename the files and the code should run seamlessly!
